### ISSUE TITLE
Feature Request:  Ability to rotate button mapping

### ISSUE THREAD

**Issue by SegaSnatcher** [bootsector/LLOAD#5]
There is a handy feature within Gamer Pro/Blisster where you can hold 4 face buttons + start and it will rotate the controller mapping.   So say you want to use a SNES controller on GBA core via LLAPI, but don't like having to use the B and A buttons, you simply hold 4 buttons + Start for a few seconds and it will rotate the mapping so that Y functions as the B button and B functions as the A button.  This makes playing GBA with a SNES controller much more enjoyable.

**Comment by bootsector** [comment]
In order to keep consistency with what MiSTer already provides for USB controllers, best approach would be adding mapping capabilities inside LLAPI cores. More logic added to the controller adapter, more lag we get.
In case LLAPI input mapping is not under anyone's roadmap, I will think about some simple input profiles switching in the future. No ETA on this, though.

**Comment by bootsector** [comment]
No mapping is planned for LLAPI. Actually, LLAPI support should be completely removed in the near future since it's not MiSTer official.
